server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eurekastandalone.com:7900/eureka/

spring:
  application:
    name: provider2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distribute?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    #最大连接数
    max-active: 1000
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 60000
    filters: stat,wall
    validation-query: SELECT 'X'
    keep-alive: true
    pool-prepared-statements: true
    max-open-prepared-statements: 50
    max-pool-prepared-statement-per-connection-size: 20
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
mybatis:
  mapper-locations: classpath:mapper/*.xml
